
name: Maven release
on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      repository-projects: write
      packages: write

    steps:
    - name: Checkout main branch from Github
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        settings-path: ${{ github.workspace }} 
        server-id: github

    - name: Configure Git user
      uses: fregante/setup-git-user@v1.1.0
    
    - name: Maven Release x GitHub Packages
      run: |
        mvn -B release:prepare
        mvn release:perform -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: ncipollo/release-action@v1
      with:
        artifacts: back/target/ulp-observability-listener-*-jar-with-dependencies.jar
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}

