name: Releases

on:
  push:
    branches:
      - refs/tags/*

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v1

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: back/target/ulp-observability-listener-*-jar-with-dependencies.jar
        token : ${{ secrets.GITHUB_TOKEN }}